# Generated by Django 2.2 on 2019-05-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('Address1', models.CharField(max_length=300)),
                ('Address2', models.CharField(max_length=300)),
                ('Phone', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('unit', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('currency_type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('converted_price', models.IntegerField()),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('delivery_date', models.DateField()),
                ('unit_purchased', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.CustomerModel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.ProductModel')),
            ],
        ),
    ]
