# Generated by Django 2.2.1 on 2019-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('entry_method', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('amount', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
