# Generated by Django 2.2 on 2019-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('entry_method', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
