# Generated by Django 2.2 on 2019-09-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fName',
            field=models.CharField(blank=True, default='Pakistan', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lName',
            field=models.CharField(blank=True, default='Pakistan', max_length=20, null=True),
        ),
    ]
