# Generated by Django 2.2.1 on 2019-07-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='ntn',
            field=models.CharField(default='', max_length=50),
        ),
    ]
