# Generated by Django 2.2 on 2019-08-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_category_title'),
        ('customer', '0002_auto_20190730_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='account.Category'),
        ),
    ]
