# Generated by Django 2.2 on 2019-08-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
