# Generated by Django 2.2 on 2019-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=20)),
                ('quatity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(default='', max_length=20)),
                ('sae', models.CharField(default='', max_length=20)),
                ('api', models.CharField(default='', max_length=20)),
                ('unit', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
