# Generated by Django 2.2 on 2019-05-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('currency_type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('converted_price', models.IntegerField()),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('delivery_date', models.DateField()),
                ('unit_purchased', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
