# Generated by Django 2.2 on 2019-08-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20190811_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='category',
        ),
    ]
