# Generated by Django 2.2 on 2019-08-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20190811_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isSuperAdmin',
            field=models.BooleanField(default=True),
        ),
    ]
