# Generated by Django 2.2 on 2019-08-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicce', '0001_initial'),
        ('transaction', '0009_transaction_issuperadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoiceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicce.Invoice'),
        ),
    ]
