# Generated by Django 2.2 on 2019-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_transaction_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoiceId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
