# Generated by Django 2.2 on 2019-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20190819_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoiceId',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
