# Generated by Django 2.2 on 2019-08-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerOrderNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('buyerOrderNumberDate', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('taxInvoiceNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('taxInvoiceNumberDate', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('deliverNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('deliverNumberDate', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('qoutNumber', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('qoutNumberDate', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('residualPayment', models.IntegerField(blank=True, default=0, null=True)),
                ('subTotal', models.IntegerField(blank=True, default=0, null=True)),
                ('grandTotal', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default='Unpaid', max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overiddenPrice', models.IntegerField(default=0)),
                ('quatityOffered', models.IntegerField(default=0)),
                ('customerDescription', models.CharField(max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicce.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
