# Generated by Django 2.2.1 on 2019-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customerDescription',
            field=models.CharField(default='hgjjgj', max_length=20),
            preserve_default=False,
        ),
    ]
