# Generated by Django 2.2.1 on 2019-06-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190519_0700'),
        ('invoicce', '0002_invoice_customerdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customerDescription',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='overiddenPrice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quatityOffered',
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overiddenPrice', models.IntegerField(default=0)),
                ('quatityOffered', models.IntegerField(default=0)),
                ('customerDescription', models.CharField(max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicce.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
