# Generated by Django 2.2.1 on 2019-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicce', '0004_auto_20190619_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyerOrderNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyerOrderNumberDate',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deliverNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deliverNumberDate',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qoutNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qoutNumberDate',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxInvoiceNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxInvoiceNumberDate',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
