# Generated by Django 2.2.1 on 2019-08-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicce', '0006_auto_20190801_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, default='Unpaid', max_length=20, null=True),
        ),
    ]
